scrape_configs:
  - job_name: 'documents-api'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s # This can be adjusted based on our needs
    static_configs:
      - targets: ['host.docker.internal:8085']
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']